version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=beagle
      - POSTGRES_PASSWORD_FILE=/run/secrets/beagle_db_pass
      - POSTGRES_DB=beagleprod
    volumes:
      - beagle_pgdata:/var/lib/postgresql/data
    networks:
      - beaglenet
    secrets:
      - beagle_db_pass
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==manager"


  fe:
    image: osubalance/beagle
    ports:
      - "3000:3000"
    volumes:
      - anonftp:/var/ftp/beagle:rw
    depends_on:
      - scp
    environment:
      BEAGLE_ENV: ${BEAGLE_ENV}
    entrypoint: /beagle/beagle/environment/foreground
    secrets:
      - ad_pass
      - beagle_db_pass
      - redcap_api_token
    networks:
      - beaglenet
    deploy:
      endpoint_mode: dnsrr
      placement:
        constraints:
          - "node.role==manager"

  scp:
    image: osubalance/scp
    volumes:
      - anonftp:/var/data/beagle/data/files:rw
    ports:
      - "21:22"
    deploy:
      placement:
        constraints:
          - "node.role==manager"


volumes:
  anonftp:
  beagle_pgdata:

networks:
  beaglenet:

secrets:
  ad_pass:
    external: true
  beagle_db_pass:
    external: true
  redcap_api_token:
    external: true
