version: '3.7'
services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=beagle
      - POSTGRES_PASSWORD_FILE=/run/secrets/beagle_db_pass
      - POSTGRES_DB=beagleprod
    volumes:
      - beagle_pgdata:/var/lib/postgresql/data
    networks:
      - beaglestaging
    secrets:
      - beagle_db_pass
      - beagle_reports_pass
    ports:
      - target: 5432
        published: 5001
        mode: host

  fe:
    image: osubalance/beagle
    ports:
      - "3001:3000"
   volumes:
     - anonftp:/var/ftp/beagle:rw
   depends_on:
     - scp
    environment:
      BEAGLE_ENV: ${BEAGLE_ENV}
    entrypoint: /beagle/beagle/environment/foreground
    secrets:
      - ad_pass
      - beagle_db_pass
      - beagle_reports_pass
      - redcap_api_token
    networks:
      - beaglestaging

  scp:
    image: osubalance/scp
    volumes:
      - anonftp:/var/data/beagle/data/files:rw
    ports:
      - "21:23"
    networks:
      - beaglestaging


volumes:
  anonftp:
  beagle_pgdata:

networks:
  beaglestaging:

secrets:
  ad_pass:
    external: true
  beagle_db_pass:
    external: true
  beagle_reports_pass:
    external: true
  redcap_api_token:
    external: true
